FROM python:3.9

FROM tensorflow/tensorflow:latest-gpu

RUN mkdir /src

WORKDIR /src

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113

COPY model ./model

COPY FNdict ./

COPY LNdict ./

COPY scripts ./scripts

COPY main.py ./

CMD [ "python", "-u", "./main.py" ]
