FROM python:3.9

RUN mkdir /src

WORKDIR /src

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY model ./model

COPY scripts ./scripts

COPY main.py ./

CMD [ "python", "-u", "./main.py" ]
